FROM debian:latest
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip ipython3 sudo && \
    apt-get clean all && \
    useradd -ms /bin/bash jeremy && echo "jeremy:jeremy" | chpasswd && \
    adduser jeremy sudo
RUN echo "echo Mon Sep 11 23:40:09 UTC 2015" > /usr/bin/date && chmod 755 /usr/bin/date
USER jeremy
WORKDIR /home/jeremy
