#!/usr/bin/bash

if [ $1 = "2014-01-09" ]; then
    host="dave-nb";
    docker run -i -t -h $host $1 /bin/bash;
    host="pcjeremy";
    docker run -i -t -h $host debian-demo /bin/bash;
else 
    host="mcyprian-pc"
    docker run -i -t -h $host $1 /bin/bash;
fi  
